version: '3.8'

services:
  app:
    build: 
      context: .
      target: builder
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    depends_on:
      - redis
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-8000}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=abc5572232
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: 