version: '3.8'

services:
  app:
    image: chenzhihua/blog-server:${TAG:-latest}
    build:
      context: .
      target: prod
    restart: unless-stopped
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-8000}
      - REDIS_URL=redis://redis:6379
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      placement:
        constraints:
          - node.role == worker

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local 